### ISSUE TITLE
Enviar email negando admissão

### ISSUE THREAD

**Issue by Aluno21530** [iptomar/Tech-Art-B#45]
Deve ser implementada a funcionalidade de enviar um email para o utilizador caso sua admissão ao TechnArt não seja aceita.

**Comment by diogop2002** [comment]
Da mesma forma que se envia um email quando é aceite uma admissão, para quando o administrador não acha que a pessoa que fez a admissão tem os critérios para ser investigador no TechnArte e apaga a admissão deste, é enviado um email para a pessoa que a sua admissão foi recusada.
