### ISSUE TITLE
Criar link no site com os regulamentos do Centro de Investigação

### ISSUE THREAD

**Issue by joaomfsalvador** [iptomar/Tech-Art-B#7]
Criar link no site com os regulamentos do Centro de Investigação que está contido em: Investigadores/as Techn&Art | Geral | Microsoft Teams.

**Comment by diogop2002** [comment]
Em vez de link para o google drive, colocou-se o ficheiro de regulamento do (TECHN&ART) no projeto para este ficheiro ser sempre acessível.
Esta acessível agora localmente
